[tool.black]
line-length=90


#Pylint section
[tool.pylint]
[tool.pylint.master]
ignore='old_test/'

[tool.pylint.'BASIC']
module-naming-style='PascalCase'
class-naming-style='PascalCase'

[tool.pylint.'MESSAGES CONTROL']
disable = ['I1101']

